name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub using docker/login-action
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t architjain138/ci-cd_pipeline:latest .

    # Push the Docker image to DockerHub
    - name: Push to DockerHub
      run: docker push architjain138/ci-cd_pipeline:latest
